Update gradle config
connexta/ion-cicd pull request #15
Opened 2019-09-11 17:37 UTC by CPUcontrol

2019-09-16 22:23 UTC, j-fontaine requested changes

2019-09-16 22:23 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +          name: Maven install without tests
The name field here still references Maven

2019-09-16 22:23 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +            ./gradlew install -B -DskipTests $DISABLE_DOWNLOAD_PROGRESS_OPTS
The $DISABLE_DOWNLOAD_PROGRESS_OPTS environment variable generates maven plugin logger guidance. I suspect it won't work properly for gradle.  Have you run this manually to confirm it works as expected?

The same concern exists for me around the -DskipTests command.  We should review and have some guidance around the gradle file and the different stages it allows.

2019-09-16 22:23 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +          name: Maven test phase
Ref: Maven (see above)

2019-09-16 22:23 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +            ./gradlew test -B $DISABLE_DOWNLOAD_PROGRESS_OPTS
REF: $DISABLED_DOWNLOAD_PROGRESS_OPTS (see above)

2019-09-16 22:23 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +            echo $SONAR_PARAMS;
While this structure works for maven, I'm not certain it works for gradle.  Have you tested this?
We may need to add additional logic to allow sonar to work properly with Gradle that isn't a direct port over.

2019-09-17 12:23 UTC, aaronilovici commented on circleci/templates/gradle/config_template-v0_1.yml
> +            ./gradlew install -B -DskipTests $DISABLE_DOWNLOAD_PROGRESS_OPTS
-B (batch mode) also doesn't work. You should try these commands before putting up the PR.

2019-09-18 15:26 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +            ./gradlew clean build --info
Does this skip or execute the test phase?
The general idea with maven is that we skip the unit tests and defer them out to the next Unit Testing phase.

2019-09-18 15:26 UTC, j-fontaine commented on circleci/templates/gradle/config_template-v0_1.yml
> +            echo $SONAR_PARAMS;
Do we know if the command line arguments also still work with this or do they get ignored?

2019-09-23 11:48 UTC, j-fontaine approved these changes

2019-09-23 11:48 UTC, merged